name: clay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  receive_sharing_intent: 
    path: "../receive_sharing_intent"
  flutter_localizations:
    sdk: flutter
  
   # 앱 필수 
 

  # 파이어베이스 ------------------
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.0
  cloud_firestore_platform_interface: ^5.1.1
  cloud_firestore: ^2.5.3
  google_sign_in: ^5.0.1
  firebase_storage: ^8.0.0
  

  #SNS 로그인 --------------------
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  flutter_kakao_login: ^3.3.0

  #시스템 관련 --------------
  package_info: ^2.0.0
  path_provider: ^2.0.5
  provider: ^5.0.0
  permission_handler: ^6.1.1
  
  get: ^4.3.8
  get_storage: ^2.0.1

  #Utils 유틸리티 --------------------
  email_validator: ^2.0.1
  sprintf: ^6.0.0
  datetime_picker_formfield: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  jiffy: ^4.1.0
  community_material_icon: ^5.9.55
  material_design_icons_flutter: ^5.0.5955-rc.1

  # 화면 관련 --------------
  fluttertoast: ^8.0.1-nullsafety.0
  image: ^3.0.2
  image_picker: ^0.7.3
  webview_flutter: ^2.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.0
  intro_slider: ^2.4.0
  flutter_balloon_slider: ^0.1.1
  photo_manager: ^1.2.7

  cupertino_icons: ^1.0.2
  #스트링 관련 ---------------------
  
  
  # API 관련 ---------------------
  connectivity_plus: ^1.0.6
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.0
  http: ^0.13.0
  share: ^2.0.1
  url_launcher: ^6.0.2
  android_intent: ^2.0.2
  # dio: ^4.0.0-beta6
  
  # SNS 
  # kakao_flutter_sdk: ^0.6.0-beta.2
  flutter_cache_manager: ^3.0.0-nullsafety.2
  flutter_html: ^2.0.0-nullsafety.0
 
  mockito: ^5.0.3  
 

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  flutter_test:
    sdk: flutter
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/img/
    - assets/images/
    
    # SNS 로그인
    - assets/sns_login/google.png
    - assets/sns_login/wide_google.png
    - assets/sns_login/google_wide.png